version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    docker:
      - image: cimg/python:3.11-node
    parallelism: 4
    resource_class: large
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Instalar pytest
          command: pip install pytest
      - run:
          name: Ejecutar tests con Test Runner
          command: |
            circleci tests glob "tests/test_*.py" | \
            circleci tests run --command "xargs pytest --junitxml=junit.xml" \
              --split-by=timings \
              --timings-type=name \
              --verbose
      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: /tmp/circleci-test-results/

  flake8:
    docker:
      - image: cimg/python:3.11-node
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run flake8
          command: flake8 --ignore=E501 --exclude=.venv,.git,__pycache__ . || true

workflows:
  build-and-test:
    jobs:
      - test-python
      - flake8