version: 2.1
orbs:
  python: circleci/python@2
jobs:

  test-python:
    docker:
      - image: cimg/python:3.11-node
    parallelism: 4
    resource_class: large
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Ejecutar tests con Test Runner
          command: |
            set -e
            TEST_FILES=$(circleci tests glob "./**/test_*.py" | circleci tests split --split-by=timings)
            mkdir -p test-results
            pytest -o junit_family=xunit1 --verbose --junitxml=test-results/junit.xml $TEST_FILES
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  flake8:
    docker:
      - image: cimg/python:3.11-node
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run flake8
          command: flake8 --ignore=E501 --exclude=.venv,.git,__pycache__ . || true

workflows:
  build-and-test:
    jobs:
      - test-python
      - flake8