version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    docker:
      - image: cimg/python:3.11-node
    parallelism: 4
    resource_class: large
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Instalar dependencias de testing
          command: pip install pytest
      - run:
          name: Run tests
          command: |
            # Crear directorio para timings
            mkdir -p .circleci-test-timings
            
            # Ejecutar tests con fallback a filesize
            circleci tests glob "tests/test_*.py" | \
            circleci tests split --split-by=timings --timings-type=name || \
            circleci tests split --split-by=filesize | \
            xargs pytest --junitxml=junit.xml
            
            # Guardar timings para próximas ejecuciones
            circleci tests timings save .circleci-test-timings/timings.json
      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: .circleci-test-timings/timings.json

  flake8:
    docker:
      - image: cimg/python:3.11-node
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Install flake8
          command: pip install flake8
      - run:
          name: Run flake8
          command: flake8 --ignore=E501 --exclude=.venv,.git,__pycache__ . || true

workflows:
  build-and-test:
    jobs:
      - test-python
      - flake8