version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    docker:
      - image: cimg/python:3.11-node
    parallelism: 4
    resource_class: large
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run tests
          command: circleci tests glob "tests/*.py" | circleci tests run --command "xargs pytest --junitxml=junit.xml" --split-by=timings --timings-type=name
      - store_test_results:
          path: junit.xml
  flake8:
    docker:
      - image: cimg/python:3.11-node
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Install flake8
          command: pip install flake8
      - run:
          name: Run flake8
          command: flake8 --ignore=E501 --exclude=.venv,.git,pycache . || true
      - store_test_results:
          path: flake8.xml
workflows:
  build-and-test:
    jobs:
      - test-python
      - flake8
